// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryarharzgookeubwowgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5YXJoYXJ6Z29va2V1Yndvd2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NDAzMTMsImV4cCI6MjA1ODUxNjMxM30.jTJVmFSsDLQ3fEgOVopZQcSbGAiDXF-6yQNI0t7CWDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);